---
- name: Deploy FTP server using existing users
  hosts: ftp
  become: yes
  vars:
    ftp_allow_anonymous: false
    ftp_files_dir: /srv/ftp_files
    ftp_config_path: /etc/vsftpd.conf

  tasks:

    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
        update_cache: yes

    - name: Backup default vsftpd.conf
      copy:
        src: "{{ ftp_config_path }}"
        dest: "{{ ftp_config_path }}.bak"
        remote_src: yes

    - name: Deploy vsftpd config from template
      template:
        src: "vsftpd.conf.j2"
        dest: "{{ ftp_config_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Create FTP files directory
      file:
        path: "{{ ftp_files_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create test file in FTP directory
      copy:
        dest: "{{ ftp_files_dir }}/testfile.txt"
        content: "This is a test file for FTP validation.\n"
        owner: root
        group: root
        mode: '0644'

    - name: Restart vsftpd
      service:
        name: vsftpd
        state: restarted
        enabled: yes

    - name: Verify FTP port is listening
      shell: "ss -tulpn | grep :21"
      register: ftp_port_check
      changed_when: false

    - name: Show FTP port status
      debug:
        msg: "{{ ftp_port_check.stdout }}"

