---
- name: Deploy FTP server with templated config
  hosts: ftp
  become: yes
  vars:
    ftp_allow_anonymous: false
    ftp_user: ftpuser
    ftp_password: "SuperSecurePassword123!"
    ftp_home: "/home/{{ ftp_user }}"
    ftp_config_path: "/etc/vsftpd.conf"

  tasks:

    - name: Install vsftpd
      apt:
        name: vsftpd
        state: present
        update_cache: yes

    - name: Create FTP user (if anonymous disabled)
      user:
        name: "{{ ftp_user }}"
        password: "{{ ftp_password | password_hash('sha512') }}"
        shell: /usr/sbin/nologin
        home: "{{ ftp_home }}"
        state: present
      when: not ftp_allow_anonymous

    - name: Create FTP home directory
      file:
        path: "{{ ftp_home }}"
        state: directory
        owner: "{{ ftp_user }}"
        group: "{{ ftp_user }}"
        mode: '0755'
      when: not ftp_allow_anonymous

    - name: Backup default vsftpd.conf
      copy:
        src: "{{ ftp_config_path }}"
        dest: "{{ ftp_config_path }}.bak"
        remote_src: yes

    - name: Deploy vsftpd config from template
      template:
        src: "vsftpd.conf.j2"
        dest: "{{ ftp_config_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Restart vsftpd
      service:
        name: vsftpd
        state: restarted
        enabled: yes

    - name: Verify FTP port is listening
      shell: "ss -tulpn | grep :21"
      register: ftp_port_check
      changed_when: false

    - name: Show FTP port status
      debug:
        msg: "{{ ftp_port_check.stdout }}"

