---
- name: Deploy and Configure FTP Server
  hosts: ftp_server
  become: true

  vars:
    # Users defined in competition.yaml
    ftp_users:
      - username: "ttesterson"
        password: "testpass"
      - username: "rpeterson"
        password: "otherpass"
    
    # Scored file details from competition.yaml
    scored_file_path: "ftp_files"
    scored_file_name: "testfile.txt"
    scored_file_content: "Sample file contents"

  tasks:
    - name: Install vsftpd package
      ansible.builtin.apt:
        name: vsftpd
        state: present
        update_cache: yes

    - name: Push vsftpd configuration file
      ansible.builtin.template:
        src: templates/vsftpd.conf.j2
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart vsftpd

    - name: Create FTP users
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      loop: "{{ ftp_users }}"

    - name: Create scored directory and file for each user
      ansible.builtin.include_tasks:
        file: tasks/create_user_files.yml
      loop: "{{ ftp_users }}"
      loop_control:
        loop_var: current_user

    - name: Ensure vsftpd service is started and enabled
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: yes

  handlers:
    - name: Restart vsftpd
      ansible.builtin.service:
        name: vsftpd
        state: restarted
